#notion importer

name: Notion Import

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "17"
    - run: npm install
    - run: npm run import
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
